### PR TITLE
Add Jenkins repo

### PR DESCRIPTION
**Pull request by gsanchezu**
Add Jenkins plugin page link and Jenkins repo

### CODE REVIEW

**Comment by gsanchezu** [comment]
@oserna3 👍?

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.0.49.54 and Jenkins instance at https://10.0.49.55

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/35/ for more details.

**Comment by oserna3** [comment]
ACK for sure!

**Comment by gsanchezu** [comment]
@osanjuan, ↘️ ↙️ ?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-q7sl36, https://ops.elasticbox.com/services/instances/i-g1neb0

**Pull request merged**
