### PR TITLE
[EBE-3805] JKP: Jenkins Kubernetes Plugin: license in files

### PR DESCRIPTION
**Pull request by gsanchezu**
@oserna3 ACK?

### CODE REVIEW

**Comment by gsanchezu** [comment]
Jenkins, test this please, now that you have the hook configured, majete!

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/27/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please, again

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/28/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please, again 2

**Comment by allyourbotsarebelongtous** [comment]
Build FAILED. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/30/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please, again 3

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.0.48.255 and Jenkins instance at https://10.0.49.0

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/31/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again to install the plugin properly

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.0.48.255 and Jenkins instance at https://10.0.49.0

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/32/ for more details.

**Comment by gsanchezu** [comment]
Jenkins, test this please again, the changes were not saved in the job! 👍

**Comment by allyourbotsarebelongtous** [comment]
Deployed ElasticKube instance is available at http://10.0.48.255 and Jenkins instance at https://10.0.49.0

**Comment by allyourbotsarebelongtous** [comment]
Build finished SUCCESSFULLY. See http://jenkins.elasticbox.com/job/ebx_pull_request_jenkins_plugin_kubernetes/33/ for more details.

**Comment by gsanchezu** [comment]
@oserna3  👍?

**Comment by oserna3** [comment]
sounds good for me :-)

**Comment by gsanchezu** [comment]
@osanjuan 👍?

**Comment by allyourbotsarebelongtous** [comment]
The following instances are being terminated: https://elasticbox.com/services/instances/i-2ks3n0, https://ops.elasticbox.com/services/instances/i-j9cod0

**Pull request merged**
